// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExecuteRequest(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ExecuteRequest'](arg1, arg2, arg3, arg4);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetEnv(arg1) {
  return window['go']['main']['App']['GetEnv'](arg1);
}

export function GetEnvForProject(arg1, arg2) {
  return window['go']['main']['App']['GetEnvForProject'](arg1, arg2);
}

export function GetFileTree() {
  return window['go']['main']['App']['GetFileTree']();
}

export function GetFileTreeForProject(arg1) {
  return window['go']['main']['App']['GetFileTreeForProject'](arg1);
}

export function GetProjectPath() {
  return window['go']['main']['App']['GetProjectPath']();
}

export function ListEnvs() {
  return window['go']['main']['App']['ListEnvs']();
}

export function ListEnvsForProject(arg1) {
  return window['go']['main']['App']['ListEnvsForProject'](arg1);
}

export function OpenProject() {
  return window['go']['main']['App']['OpenProject']();
}

export function ParseRequest(arg1) {
  return window['go']['main']['App']['ParseRequest'](arg1);
}

export function ReadRequest(arg1) {
  return window['go']['main']['App']['ReadRequest'](arg1);
}

export function ReadRequestFromProject(arg1, arg2) {
  return window['go']['main']['App']['ReadRequestFromProject'](arg1, arg2);
}

export function SaveEnv(arg1, arg2) {
  return window['go']['main']['App']['SaveEnv'](arg1, arg2);
}

export function SaveEnvForProject(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveEnvForProject'](arg1, arg2, arg3);
}

export function SaveRequest(arg1, arg2) {
  return window['go']['main']['App']['SaveRequest'](arg1, arg2);
}

export function SaveRequestToProject(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveRequestToProject'](arg1, arg2, arg3);
}

export function SetProjectPath(arg1) {
  return window['go']['main']['App']['SetProjectPath'](arg1);
}

export function SyncProject(arg1) {
  return window['go']['main']['App']['SyncProject'](arg1);
}
