// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function ExecuteRequest(arg1:string,arg2:string,arg3:string,arg4:Record<string, string>):Promise<models.RunResult>;

export function GetConfig():Promise<models.HttxConfig>;

export function GetEnv(arg1:string):Promise<models.EnvVariables>;

export function GetEnvForProject(arg1:string,arg2:string):Promise<models.EnvVariables>;

export function GetFileTree():Promise<Array<models.FileTreeNode>>;

export function GetFileTreeForProject(arg1:string):Promise<Array<models.FileTreeNode>>;

export function GetProjectPath():Promise<string>;

export function ListEnvs():Promise<Array<string>>;

export function ListEnvsForProject(arg1:string):Promise<Array<string>>;

export function OpenProject():Promise<string>;

export function ParseRequest(arg1:string):Promise<models.ParsedHttpRequest>;

export function ReadRequest(arg1:string):Promise<string>;

export function ReadRequestFromProject(arg1:string,arg2:string):Promise<string>;

export function SaveEnv(arg1:string,arg2:models.EnvVariables):Promise<void>;

export function SaveEnvForProject(arg1:string,arg2:string,arg3:models.EnvVariables):Promise<void>;

export function SaveRequest(arg1:string,arg2:string):Promise<void>;

export function SaveRequestToProject(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetProjectPath(arg1:string):Promise<void>;

export function SyncProject(arg1:string):Promise<string>;
